#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-bluetooth
Version  : 3.20.1
Release  : 1
URL      : https://download.gnome.org/sources/gnome-bluetooth/3.20/gnome-bluetooth-3.20.1.tar.xz
Source0  : https://download.gnome.org/sources/gnome-bluetooth/3.20/gnome-bluetooth-3.20.1.tar.xz
Summary  : Widgets for Bluetooth device selection
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: gnome-bluetooth-bin
Requires: gnome-bluetooth-lib
Requires: gnome-bluetooth-data
Requires: gnome-bluetooth-doc
Requires: gnome-bluetooth-locales
BuildRequires : desktop-file-utils
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : libxml2-dev
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gdk-3.0)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libcanberra-gtk3)
BuildRequires : pkgconfig(libnotify)
BuildRequires : pkgconfig(libudev)

%description
GNOME Bluetooth
===============
gnome-bluetooth is a fork of bluez-gnome focused on integration with
the GNOME desktop environment.

%package bin
Summary: bin components for the gnome-bluetooth package.
Group: Binaries
Requires: gnome-bluetooth-data

%description bin
bin components for the gnome-bluetooth package.


%package data
Summary: data components for the gnome-bluetooth package.
Group: Data

%description data
data components for the gnome-bluetooth package.


%package dev
Summary: dev components for the gnome-bluetooth package.
Group: Development
Requires: gnome-bluetooth-lib
Requires: gnome-bluetooth-bin
Requires: gnome-bluetooth-data
Provides: gnome-bluetooth-devel

%description dev
dev components for the gnome-bluetooth package.


%package doc
Summary: doc components for the gnome-bluetooth package.
Group: Documentation

%description doc
doc components for the gnome-bluetooth package.


%package lib
Summary: lib components for the gnome-bluetooth package.
Group: Libraries
Requires: gnome-bluetooth-data

%description lib
lib components for the gnome-bluetooth package.


%package locales
Summary: locales components for the gnome-bluetooth package.
Group: Default

%description locales
locales components for the gnome-bluetooth package.


%prep
%setup -q -n gnome-bluetooth-3.20.1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1492047005
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1492047005
rm -rf %{buildroot}
%make_install
%find_lang gnome-bluetooth2

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bluetooth-sendto

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GnomeBluetooth-1.0.typelib
/usr/share/applications/bluetooth-sendto.desktop
/usr/share/applications/mimeinfo.cache
/usr/share/gir-1.0/*.gir
/usr/share/gnome-bluetooth/pin-code-database.xml
/usr/share/icons/hicolor/16x16/apps/bluetooth.png
/usr/share/icons/hicolor/16x16/status/bluetooth-active.png
/usr/share/icons/hicolor/16x16/status/bluetooth-disabled.png
/usr/share/icons/hicolor/16x16/status/bluetooth-paired.png
/usr/share/icons/hicolor/22x22/apps/bluetooth.png
/usr/share/icons/hicolor/22x22/status/bluetooth-active.png
/usr/share/icons/hicolor/22x22/status/bluetooth-disabled.png
/usr/share/icons/hicolor/22x22/status/bluetooth-paired.png
/usr/share/icons/hicolor/24x24/apps/bluetooth.png
/usr/share/icons/hicolor/24x24/status/bluetooth-active.png
/usr/share/icons/hicolor/24x24/status/bluetooth-disabled.png
/usr/share/icons/hicolor/24x24/status/bluetooth-paired.png
/usr/share/icons/hicolor/32x32/apps/bluetooth.png
/usr/share/icons/hicolor/32x32/status/bluetooth-active.png
/usr/share/icons/hicolor/32x32/status/bluetooth-disabled.png
/usr/share/icons/hicolor/32x32/status/bluetooth-paired.png
/usr/share/icons/hicolor/48x48/apps/bluetooth.png
/usr/share/icons/hicolor/48x48/status/bluetooth-active.png
/usr/share/icons/hicolor/48x48/status/bluetooth-disabled.png
/usr/share/icons/hicolor/icon-theme.cache
/usr/share/icons/hicolor/scalable/apps/bluetooth.svg
/usr/share/icons/hicolor/scalable/status/bluetooth-paired.svg

%files dev
%defattr(-,root,root,-)
/usr/include/gnome-bluetooth/bluetooth-chooser-button.h
/usr/include/gnome-bluetooth/bluetooth-chooser-combo.h
/usr/include/gnome-bluetooth/bluetooth-chooser.h
/usr/include/gnome-bluetooth/bluetooth-client.h
/usr/include/gnome-bluetooth/bluetooth-enums.h
/usr/include/gnome-bluetooth/bluetooth-filter-widget.h
/usr/include/gnome-bluetooth/bluetooth-settings-widget.h
/usr/include/gnome-bluetooth/bluetooth-utils.h
/usr/lib64/libgnome-bluetooth.so
/usr/lib64/pkgconfig/gnome-bluetooth-1.0.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
/usr/share/gtk-doc/html/gnome-bluetooth/BluetoothChooser.html
/usr/share/gtk-doc/html/gnome-bluetooth/BluetoothChooserButton.html
/usr/share/gtk-doc/html/gnome-bluetooth/BluetoothChooserCombo.html
/usr/share/gtk-doc/html/gnome-bluetooth/BluetoothClient.html
/usr/share/gtk-doc/html/gnome-bluetooth/api-index-full.html
/usr/share/gtk-doc/html/gnome-bluetooth/ch01.html
/usr/share/gtk-doc/html/gnome-bluetooth/gnome-bluetooth-bluetooth-enums.html
/usr/share/gtk-doc/html/gnome-bluetooth/gnome-bluetooth-bluetooth-utils.html
/usr/share/gtk-doc/html/gnome-bluetooth/gnome-bluetooth.devhelp2
/usr/share/gtk-doc/html/gnome-bluetooth/home.png
/usr/share/gtk-doc/html/gnome-bluetooth/index.html
/usr/share/gtk-doc/html/gnome-bluetooth/left-insensitive.png
/usr/share/gtk-doc/html/gnome-bluetooth/left.png
/usr/share/gtk-doc/html/gnome-bluetooth/object-tree.html
/usr/share/gtk-doc/html/gnome-bluetooth/right-insensitive.png
/usr/share/gtk-doc/html/gnome-bluetooth/right.png
/usr/share/gtk-doc/html/gnome-bluetooth/style.css
/usr/share/gtk-doc/html/gnome-bluetooth/up-insensitive.png
/usr/share/gtk-doc/html/gnome-bluetooth/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgnome-bluetooth.so.13
/usr/lib64/libgnome-bluetooth.so.13.0.1

%files locales -f gnome-bluetooth2.lang
%defattr(-,root,root,-)

